using DevExpress.DataAccess.ObjectBinding;
using DevExpress.XtraBars;
using DevExpress.XtraReports.UI;
using QL_HoaDon.BLL;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;

namespace QL_HoaDon.GUI
{
    public partial class ThongKeHoaDon_Control : DevExpress.XtraEditors.XtraUserControl
    {
        HoaDonBLL hdbll = new HoaDonBLL();
        public ThongKeHoaDon_Control()
        {
            InitializeComponent();



            // This line of code is generated by Data Source Configuration Wizard
            hoaDonBanTableAdapter1.Fill(quanLyHoaDonDataSet1.HoaDonBan);
        }
        void bbiPrintPreview_ItemClick(object sender, ItemClickEventArgs e)
        {
        }
        public class Customer
        {
            [Key, Display(AutoGenerateField = false)]
            public int ID { get; set; }
            [Required]
            public string Name { get; set; }
            public string Address { get; set; }
            public string City { get; set; }
            public string State { get; set; }
            [Display(Name = "Zip Code")]
            public string ZipCode { get; set; }
            public string Phone { get; set; }
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }
        void LoadDSTKbyDate(DateTime fromDate, DateTime toDate)
        {
            dtgvThongKe.DataSource = HoaDonBLL.LoadDSHDbyDate(fromDate, toDate);

        }

        private void btnSearchdtd_Click(object sender, EventArgs e)
        {
            LoadDSTKbyDate(cbFromdate.DateTime,cbTodate.DateTime);
        }

        private void xtraTabPage1_Paint(object sender, System.Windows.Forms.PaintEventArgs e)
        {

        }

        private void ThongKeHoaDon_Control_Load(object sender, EventArgs e)
        {
            LoadDSHD();
            LoadCustomer();
        }
        void LoadCustomer()
        {
            cbGetCustomer.DataSource = HoaDonBLL.LoadCustomer();
            cbGetCustomer.DisplayMember = "NguoiMuaHang";
        }

        private void btnSearchuser_Click(object sender, EventArgs e)
        {
            LoadDSHDbyCustomer(cbGetCustomer.Text);
        }
        void LoadDSHDbyCustomer(string name)
        {
            dtgvThongKe.DataSource = HoaDonBLL.LoadDSHDbyCustomer(name);
        }

        private void btnRefresh_Click(object sender, EventArgs e)
        {
            LoadDSHD();
        }
        void LoadDSHD()
        {
            DataTable _dshd = HoaDonBLL.LayDSHD();
            dtgvThongKe.DataSource = _dshd;
        }
        void LoadReport()
        {
        }

        private void xtraTabPage2_Paint(object sender, System.Windows.Forms.PaintEventArgs e)
        {

        }

        private void resourcesComboBoxControl1_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            LoadReport();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            XtraReport1 report = new XtraReport1();

            report.Parameters["SoHD"].Value =Convert.ToInt32(resourcesComboBoxControl1.Text);
            report.Parameters["SoHD"].Visible = false;



            ReportDesignTool designTool = new ReportDesignTool(report);
            designTool.ShowRibbonDesignerDialog();
        }
    }
}
